### ISSUE TITLE
Questions about geneiv function

### ISSUE THREAD

**Issue by ashnair1** [mortcanty/CRC4Docker#26]
Hi @mortcanty 

I had 2 questions about the [geneiv](https://github.com/mortcanty/CRC4Docker/blob/e52a6e88d4469284a071c0b96d009f6684dbb2ea/src/auxil/auxil1.py#L179) function. 

1. Is there a particular reason you went the Cholesky decomposition route?

I understand that numpy's [eig](https://numpy.org/doc/stable/reference/generated/numpy.linalg.eig.html) function doesn't directly solve the generalised eigenproblem (Ax = λBx) as it doesn't accept a B parameter. But scipy's [eig](https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.eig.html) function does. 

Comparing the two implementations below, you get the same eigenvalues and (scaled) eigenvectors so they are equivalent.

```
import scipy as sp
import numpy as np

def geneivprob(A,B):
    # Using scipy
    lamda, eigvec = sp.linalg.eig(A, B)
    return lamda, eigvec

def geneivprob2(A,B):
    """
    CRC4 method
    Reduce the problem to a standard symmetric eigenvalue problem
    Ax = λBx -> Cy = λy    
    """
    Linv = np.linalg.inv(np.linalg.cholesky(B))
    C = Linv @ A @ Linv.transpose()
    #C = np.asmatrix((C + C.transpose())*0.5,np.float32)
    lamda,V = np.linalg.eig(C)
    return lamda, Linv.transpose() @ V   
```

So did you go the Cholesky decomposition route becuase:
- It was more efficient
- To solve the problem in pure numpy

2. What was the purpose of this line `C = np.asmatrix((C + C.transpose())*0.5,np.float32)`?

**Comment by mortcanty** [comment]
For didactic reasons. The Cholesky decomposition is derived in an Appendix of my book, and in the text the solution of the geneiv problem is explained in terms of it.  So less of a black box for the reader. 

Another reason was for the implementation of iMAD on the GEE (Python or JS), since there is an ee.Array.matrixCholeskyDecomposition() but no ee.Array.matrixGeneiv().

Re 2. I seem to recall I was getting a "non-symmetric matrix" error for C and assumed it was some kind of rounding problem. Whatever it was, the fix got rid of it.

**Comment by ashnair1** [comment]
Thanks for the clarification
